sudo: true
dist: trusty
group: deprecated-2017Q3
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# install pg_chameleon
install: "pip install ."

services:
  - mysql

env:
   - MYVER='5.6'
   - MYVER='5.7'

addons:
  postgresql: "9.6"
  
before_script:
 - tests/setup_db.sh
 
 # command to run tests
script: tests/test.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/166d0e880973f957205f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

Your unique webhook url for this service:
